### ISSUE TITLE
Action column position is not changing dynamically

### ISSUE THREAD

**Issue by nichita-pasecinic** [KevinVandy/material-react-table#482]
### material-react-table version

v1.10.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

if `positionActionsColumn` is in state and is getting changed, I'm expecting so that column orders would change too

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-wtvpnu?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I guess we will fix this, but it might be better to handle the `columnOrder` in the `state` manually if you are already planning on mutating the column order like that.

**Comment by KevinVandy** [comment]
I'm actually considering removing the `positionActionsColumn` prop in a future 2.0 version. Column Order State should drive all column order stuff. This prop just leads to bugs

**Comment by nichita-pasecinic** [comment]
Agree, I've just used the column order state with `mrt-row-actions` in the right position and removed the `positionActionsColumn`

**Comment by nicolaeClichici** [comment]
Hello, have sort of same problem: 
Table have some columns -> On some effect conditionally is added a column on the second position in columns ordering but table is displaying this column as the last column. 
Fixed by initializing the initial column order state.

**Comment by KevinVandy** [comment]
The `positionActionsColumn` table option still exists for convience, but if you ever run into this problem, just manage the `columnOrder` state manually.
