### ISSUE TITLE
Column filtered item gets lost after toggling the "Show/ Hide filters" button.

### ISSUE THREAD

**Issue by quyle92** [KevinVandy/material-react-table#608]
### material-react-table version

1.8.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

After applying filters to a column, and then clicking the "Show/ Hide filters" button to hide the filtered column input, then clicking again to turn it on, the filtered item disappears (which it should not be intuitively and if it does disappear, then there must be a property that triggers this event so that I can call my backend api again to re-populate the table).

### Minimal, Reproducible Example - (Optional, but Recommended)

```
<MaterialReactTable
          enableStickyHeader
          getRowId={(row) => row.id} //give each row a more useful id
          columns={columns}
          data={rows}
          muiToolbarAlertBannerProps={
              isError
                  ? {
                        color: 'error',
                        children: 'Error loading data',
                    }
                  : undefined
          }
          rowCount={rowCount}
          state={{
              isLoading,
              pagination,
              showAlertBanner: isError,
          }}
          positionPagination="top"
          enableGlobalFilter={false}
          enableColumnFilterModes={false}
          enableSorting={false}
          manualFiltering
          onColumnFiltersChange={function (updater) {
              const newColumnFilters = updater(columnFilters);
              dispatch(setColumnFilters(newColumnFilters));
              dispatch(fetchPlayerInventories({ navigate, setIsError }));
          }}
          initialState={{ showColumnFilters: true }}
          muiTablePaginationProps={{
              count: rowCount,
          }}
          manualPagination
          onPaginationChange={function (updater) {
              const nextPagination = updater(pagination);
              dispatch(setPagination(nextPagination));
              dispatch(fetchPlayerInventories({ navigate, setIsError }));
          }}
          onShowColumnFiltersChange={function () {
              console.log('first'); // I think this prop would trigger the event upon toggling the "Show/ Hide filters" button but it did not.
          }}
/>
```

### Screenshots or Videos (Optional)

![ezgif-5-018934e387](https://github.com/KevinVandy/material-react-table/assets/59790219/56188b5b-ae3d-4170-b523-a09d98df02db)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think this was fixed a long time ago. Just upgrade to the most recent version

**Comment by quyle92** [comment]
thanks but I am using the latest version which is "material-react-table": "^1.14.0".
But it still persists.
